wrapperVersion=3.3.4
distributionType=only-script
<<<<<<< HEAD
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.14/apache-maven-3.9.14-bin.zip
=======
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.12/apache-maven-3.9.12-bin.zip
>>>>>>> d88c161f5c1b4e016ea77915b9d3e1726fa0c98f
