spring.application.name=spring_project
spring.mvc.view.prefix=WEB-INF/pages/
spring.mvc.view.suffix=.jsp
server.port=9090

spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/resources/**